### ISSUE TITLE
NCI: multiple identifiers pick up by the xslt file.

### ISSUE THREAD

**Issue by jbw900** [researchgraph/Crosswalks#47]
When I translate researchers to the Graph schema, there are multiple identifiers of researchers. I would like to pick ORCID if it is available, or one of the persistent identifier if ORCID is not available, but don't know how to filter it.

**Comment by aaryani** [comment]
Given we only have ORCID and no local_id for the researcher: https://github.com/researchgraph/Crosswalks/blob/master/nci.org.au/one_dataset_record-input.xml#L532

We should create a relation object between the dataset and ORCID identifier. 

The outcome will be something like

```
      <relation>
         <from_key>researchgraph.org/NCI/55d57c84ce4e0</from_key>
         <to_uri>http://orcid.org/0000-0003-2523-1676</to_uri>
         <label>relatedTo</label>
      </relation>
```

We can use figshare crosswalk as an example: https://github.com/researchgraph/Crosswalks/blob/master/figshare.com/figshareRDF_to_researchgraph.xsl#L188

**Comment by aaryani** [comment]
Then we can transform email to a local_id by
- replacing "." with "-dot-"
- replacing "@" with "-at-"

In this case, the relation will be something like:
      <relation>
         <from_key>researchgraph.org/NCI/55d57c84ce4e0</from_key>
         <to_uri>researchgraph.org/NCI/jingbo-dot-wang-at-nci-dot-org-dot-au</to_uri>
         <label>relatedTo</label>
      </relation>

**Comment by aaryani** [comment]
We moving to a new architecture.
