### ISSUE TITLE
Figshare:  title: weneedtotalkaboutzinespresentation.pptx Daniel Wee

### ISSUE THREAD

**Issue by aaryani** [researchgraph/Crosswalks#63]
The is a wrong title 
 <title>weneedtotalkaboutzinespresentation.pptx Daniel Wee</title>
in 
https://github.com/researchgraph/Crosswalks/blob/master/figshare.com/samplefigshare596-output.xml#L101

**Comment by aaryani** [comment]
https://github.com/researchgraph/Crosswalks/blob/master/figshare.com/samplefigshare596.xml#L101
https://github.com/researchgraph/Crosswalks/blob/master/figshare.com/samplefigshare596-output.xml#L101

**Comment by seiya0914** [comment]
solved
