### ISSUE TITLE
VIVO: label for the person should be family name, given name

### ISSUE THREAD

**Issue by aaryani** [researchgraph/Crosswalks#69]
Reported by Michael:
"The label for the person should be family name, given name. Currently it is given, given."

**Comment by aaryani** [comment]
@mconlon17 
It seems all records have givenName and familyName such as

https://github.com/researchgraph/Crosswalks/blob/master/vivoweb.org/graphml-sample1-output.xml#L99
```
            <vcard:hasName>
               <vcard:Name rdf:about="http://vivo.mydomain.edu/individual/n72368075">
                  <vcard:givenName>JENNIFER</vcard:givenName>
                  <vcard:familyName>KRAFCHEK</vcard:familyName>
               </vcard:Name>
            </vcard:hasName>
```

I think we need more info about this issue.

**Comment by mconlon17** [comment]
Fixed on line 188
