### ISSUE TITLE
VIVO: change DOI url and remove www.

### ISSUE THREAD

**Issue by aaryani** [researchgraph/Crosswalks#71]
Reported by @mconlon17 
doi.org(http://doi.org) has changed its URLs recently. www.doi.org/doi_value(http://www.doi.org/doi_value) no longer resolves. Should be https://doi.org/doi_value. AnyURL of the for http://www.doi.org/doi_value should be replaced with http://doi.org/doi_value

**Comment by aaryani** [comment]
This is related to both publications and datasets

**Comment by aaryani** [comment]
We could not find any example of www.doi in the sample files
https://github.com/researchgraph/Crosswalks/blob/master/vivoweb.org/graphml-sample2-output.xml
https://github.com/researchgraph/Crosswalks/blob/master/vivoweb.org/graphml-sample1-output.xml

**Comment by mconlon17** [comment]
Agree.  Report was from earlier work.  No wwww.doi in the current data.
